### ISSUE TITLE
Paren-matching goes into strings

### ISSUE THREAD

**Issue by artagnon** [atom/language-c#109] opened 2016-01-06 10:57 UTC
The '{' and '}' characters are matched with characters within a string-quote or character-quote.

<img width="250" alt="screen shot 2016-01-06 at 4 24 08 pm" src="https://cloud.githubusercontent.com/assets/37226/12141030/3fc569c2-b492-11e5-8515-0c0af0d07cb8.png">

**Comment by 50Wliu** [comment] 2016-01-06 13:58
This is a duplicate of atom/bracket-matcher#78 - please subscribe there for updates.

**Closed by 50Wliu** 2016-01-06 13:58 UTC
