### ISSUE TITLE
Please improve 'intellisense' like features

### ISSUE THREAD

**Issue by Raj2032** [atom/language-c#261] opened 2018-01-24 10:26 UTC
This C++ package support is not very great. For example if I type this

int main()

As soon as I getting a suggestion to add the main function this is what I get

int int main(int argc, char const argv[]) {
/ code */
return 0;
}

See how it repeats int twice and how it adds “int argc, char const *argv[]” when I did not want this to be added.

On top of that it uses the egyption style braces rather than this style
int main()
{
// Code
}

Here is another example if this issue,

When I type "cout" this is what I get instead
"std::cout << "/* message */" << '\n';"

Firstly I have already defined the std namespace "using namespace std;" so why do I need std to be added before the cout command?

Second of all why can't it do this instead "cout << "/* message */" << endl;"

Is it possible to at least add some settings to change all of these issues mentioned above, to make the experience more like Visual Studio IDE?

**Comment by Ben3eeE** [comment] 2018-01-24 10:44
Thanks for taking the time to contribute!

Closing as a duplicate of https://discuss.atom.io/t/are-there-any-good-c-support-for-atom/51788/3.

**Closed by Ben3eeE** 2018-01-24 10:44 UTC
Labels: duplicate, question

**Comment by Raj2032** [comment] 2018-01-24 10:47
Hey man,

Where I have posted this issue on the othersite is where I am asking for a replacement package, over here I am trying to give suggestions. are you able to report bugs on the other site as well?

Do you know how to fix this issue?

**Comment by Ben3eeE** [comment] 2018-01-24 11:08
As `@DamnedScholar` replied in that topic these are snippets. They take some text (in this case `main`) and replace it with something else (in this case `int main(int argc, char const *argv[]) {\n\t${1:/* code */}\n\treturn 0;\n}`.

Since you type `int main` and then replace `main` with the above text `int` will be repeated.

We are not interested in changing the default snippets to another code style. If you want to change them you can configure them in your `snippets.cson` file. Available in the menu `File -> Snippets..`

See: http://flight-manual.atom.io/using-atom/sections/snippets/

**Comment by Raj2032** [comment] 2018-01-24 11:57
How would I do this specifically for Language-C? When I opened the
snippets, there is nothing their but comments. How come this is happening?

**Comment by DamnedScholar** [comment] 2018-01-25 07:51
There is nothing in `snippets.cson` because you haven't added anything to it. `snippets.cson` *does not* show you what snippets are currently active. It is a plain text file for you to put your own snippets, which will override built-in ones if they have the same name and scope.

**Comment by Raj2032** [comment] 2018-01-25 08:08
Nevermind it has been fixed, thanks @Holland :)
