### ISSUE TITLE
C++ colorization is incorrect after a multi-line ? : expression.

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#196] opened 2017-01-10 03:32 UTC
_From @sean-mcmanus on January 9, 2017 19:28_

- VSCode Version: 1.8.1
- OS Version: Windows (I assume Linux/OSX too).

Steps to Reproduce:

1. Use this code in a .cpp file.
long A() {
    return true ?
        Sum() : 0;
}

class Bar {

};

Bug: "class Bar" is white instead of colored correctly. It's a bug with textmate, atom, or whatever other thing VS code users for colorization.

This report is from https://github.com/Microsoft/vscode-cpptools/issues/438 .

_Copied from original issue: Microsoft/vscode#18337_

**Comment by 50Wliu** [comment] 2017-01-10 03:43
Cannot reproduce using latest language-c version, assuming fixed by #179.
![image](https://cloud.githubusercontent.com/assets/2766036/21793171/f82388d0-d6bc-11e6-9dbd-871830a48142.png)

**Closed by 50Wliu** 2017-01-10 03:43 UTC
