### ISSUE TITLE
Colorization is incorrect with "void */*comment*/"

### ISSUE THREAD

**Issue by sean-mcmanus** [atom/language-c#315] opened 2019-01-02 21:34 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Steps to Reproduce

1. Use code like int main(void */*comment*/); in a C++ file.

**Expected behavior:** Comment is colored correctly.

**Actual behavior:** 

![image](https://user-images.githubusercontent.com/19859882/50613629-f29e8580-0e92-11e9-89d0-107929f38691.png)

**Reproduces how often:** 100%

### Versions

Atom: 1.23.3

### Other info

Repros with Atom and VS Code. Original bug report is from https://github.com/Microsoft/vscode-cpptools/issues/2988 .

**Comment by rsese** [comment] 2019-01-08 00:55
> Atom: 1.23.3
...
> Repros with Atom

Thanks for the report!  The current stable release version of Atom is 1.33.1 and Tree-sitter is now on by default.  This particular issue looks like it doesn't reproduce with Tree-sitter:

![atom-1-33-1](https://github-slack.s3.amazonaws.com/monosnap/test.c__worktest-tree-sitter_2019-01-07_18-51-47.png)

As you may have heard, we are migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this issue applies only to the first-mate grammar, we are going to close it. Please let us know if we have misunderstood the description of the problem.

**Closed by rsese** 2019-01-08 00:55 UTC

**Comment by sean-mcmanus** [comment] 2019-01-08 01:01
Okay, sorry about that -- I didn't realize I had an old version of Atom.
