### ISSUE TITLE
C++ support missing for .h file

### ISSUE THREAD

**Issue by FrozenHelium** [atom/language-c#112] opened 2016-01-21 03:24 UTC
syntax highlighting is missing for C++ specific keywords (eg: class)

**Comment by 50Wliu** [comment] 2016-01-21 12:28
This is a duplicate of #85 and #89; please subscribe there for updates.

**Closed by 50Wliu** 2016-01-21 12:28 UTC

**Comment by boazsegev** [comment] 2016-11-26 18:49
This solution might provide better highlighting, but it's throwing off `lint`, which means that a lot of errors are (wrongfully) reported due to `.h` files that are actually C (not C++)...

Since some of us use C rather than C++, please consider some heuristic recognition.

Perhaps (lacking a better solution) consider allowing for a magic comment at the end of the file?

**Comment by 50Wliu** [comment] 2016-11-26 23:04
Adding a C Emacs modeline should cause Atom to switch to C.

Better heuristics are planned but are still a long way off.

**Comment by boazsegev** [comment] 2016-11-26 23:08
Thanks for the info and the update.
