### ISSUE TITLE
Syntax highlighting of parameters not working

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#285] opened 2018-09-24 19:14 UTC
_From @chengzeyi on September 23, 2018 16:2_

 

- VSCode Version: 1.27.2
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

1. Create a new cpp source code file.
2. name a local variable or a function parameter "sEnd".
```c++
bool match(string::const_iterator iterS, const string::const_iterator& sEnd, CompiledPattern::const_iterator iterP, const CompiledPattern::const_iterator& pEnd) const

int sEnd;
```
The color of "sEnd" is the same as class member's, not what it should be.
In my case,  the color should be white but in fact it is rendered to be sky blue.
Other names like siEnd don't have this problem. Is it resulted from bugs of vscode syntax highlighting engine?

Does this issue occur when all extensions are disabled?: No

_Copied from original issue: Microsoft/vscode#59186_

**Comment by Arcanemagus** [comment] 2018-09-24 22:51
It looks like this can be traced _all_ the way back to https://github.com/textmate/c.tmbundle/commit/390912121aa95cdccdc7d454a9d0f5fa282e7fcb, and the code hasn't been touched since.

In Atom at least the Tree-sitter parser can be used to work around this as it doesn't special case those, but that does little to help this case.

**Comment by chengzeyi** [comment] 2018-09-25 02:14
So this is a "feature" not a bug? Really odd old things...

**Comment by Arcanemagus** [comment] 2018-09-25 16:05
Well, at some point somebody thought it was a feature at least. _Personally_ I would call it a bug since it's only there to support something that was a legacy 13 years ago... at this point that's an antique.

I'll label it as a bug, but I don't know the language files enough to say one way or the other officially.

**Comment by lee-dohm** [comment] 2018-09-25 20:10
This doesn't appear to reproduce in Atom. Both `sEnd` and `siEnd` have the scope `source.c` associated with it. If this is only causing a problem in VSCode, then it isn't something that we're going to be investigating.

@50Wliu can you shed any more light on this?

**Comment by Arcanemagus** [comment] 2018-09-25 20:16
I was able to reproduce this when TextMate parser was enabled, are you sure you didn't have Tree-sitter enabled? That works around the issue as [previously stated](https://github.com/atom/language-c/issues/285#issuecomment-424151261).

**Comment by lee-dohm** [comment] 2018-10-01 18:35
@aeschli Do you have any suggestions on how this can be fixed? Perhaps a PR?

**Comment by lee-dohm** [comment] 2018-11-19 18:40
@aeschli Let us know if you have any suggestions here. I'm going to go ahead and close this for now.

**Closed by lee-dohm** 2018-11-19 18:40 UTC
Labels: bug, triaged
