### ISSUE TITLE
C's preprocessor directive #ifdef/#endif grays out code

### ISSUE THREAD

**Issue by Leedehai** [atom/language-c#265] opened 2018-03-18 08:24 UTC
### Description

Issues posted here: https://github.com/Microsoft/vscode-textmate/issues/63#event-1525495882

### Steps to Reproduce
**Expected behavior:**
Please, do not grey out the code because the macro is not defined, because macros may be passed in by the compiler (e.g. gcc's `-D` option).
**Actual behavior:**
Gray out the code anyway.
**Reproduces how often:**
100%.

**Comment by Arcanemagus** [comment] 2018-03-20 02:36
Using the following text from your VSCode issue:
```c
/* Update statistics. */
if (t == idle_thread)
  idle_ticks++;
#ifdef USERPROG
else if (t->pagedir != NULL)
  user_ticks++;
#endif
else
  kernel_ticks++;


#ifdef USERPROG
#include "userprog/process.h"
#endif


#ifdef FILESYS
  block_print_stats ();
#endif
  console_print_stats ();
  kbd_print_stats ();
#ifdef USERPROG
  exception_print_stats ();
#endif
```

I am unable to reproduce the behavior you are seeing there under Atom v1.25.0:
TextMate:
![image](https://user-images.githubusercontent.com/427137/37632217-635feb46-2baa-11e8-851f-3d392edd54f1.png)

Atom v1.25.0 is using [v0.59.2](https://github.com/atom/language-c/releases/tag/v0.59.2) of this grammar. Unfortunately it looks like @alexandrudima was _literally_ accurate when they said it imports from `master`: Their build process apparently has _no_ versioning applied to it for grammars so I have no idea what version of this grammar you could be using.

Atom has a command to log the scopes at a cursor location, if VSCode has something similar you can try debugging why it is marking those sections as greyed out, but since Atom isn't showing the same issue I'm going to go ahead and close this.

Thanks for taking the time to reach out!

**Closed by Arcanemagus** 2018-03-20 02:36 UTC
