### ISSUE TITLE
syntax highlight error when language-c treat a C++ .h file as a C .h file

### ISSUE THREAD

**Issue by skywind3000** [atom/language-c#125] opened 2016-03-17 07:14 UTC
most header file of C++ has the '.h' suffix, which is treated as a C header file. As a consequence of this, many C++ keywords (class, public, private, template) in the .h file get a wrong highlight.

In a ordinary .cpp file, everything in color is alright:
<img width="222" alt="48f9d1bb-57d3-4d60-a602-bbc2c8d315be" src="https://cloud.githubusercontent.com/assets/3035071/13838825/e70dedac-ec51-11e5-808b-87f372702a27.png">

After putting same piece of code to the .h file, color got issues:
<img width="273" alt="97dad0f3-50c3-48a4-a5a0-e0125578e204" src="https://cloud.githubusercontent.com/assets/3035071/13838761/801f2106-ec51-11e5-8998-6f1bb04529c5.png">

Using ctrl-shift-L to change grammar, I found .h file has been recognized as a C file by default. After changing the grammar to C++, it still has a problem around 'class':
<img width="277" alt="606650e7-c7d0-4d30-98bb-3e1f796bb7c5" src="https://cloud.githubusercontent.com/assets/3035071/13838900/5d3f72a2-ec52-11e5-9c4c-e6f02e535fcc.png">

Every C++ keywords in .h files is supposed to be recognized,  
it seems there are two issues here:

1. The .h file hasn't been treated as a cpp header file by default.
2. Keywords in .h files can not be recognized after changing the file grammar to C++.

--------------
It's very werid syntax highlight: keyword 'class' hasn't be recognized:
<img width="204" alt="f2e2b923-4b60-4cf6-8fa8-63943eeeb957" src="https://cloud.githubusercontent.com/assets/3035071/13841357/7acc2af2-ec63-11e5-91de-4b8df55d946a.png">

everything get alright if a single simicolon is added after 'NAMESPACE_BEGIN' in line 1.
<img width="193" alt="a2e93c4d-9107-44ba-952d-2ddb4686bb70" src="https://cloud.githubusercontent.com/assets/3035071/13841386/9e817ba0-ec63-11e5-9124-fca2a5396645.png">

After removing the simicolon and add the definition of NAMESPACE_BEGIN/END, I find syntax highlight error in '#endif' of line 3 but 'class' seems correct now !
<img width="302" alt="3d81f931-4717-4870-bd31-b8476e3bb404" src="https://cloud.githubusercontent.com/assets/3035071/13841428/e4b3a99a-ec63-11e5-832a-02d2826623ba.png">

**Comment by skywind3000** [comment] 2016-03-17 07:23
I can't write code any more with this wrong syntax highlight, does some one can figure me out how to fixed is locally by myself ??

**Comment by skywind3000** [comment] 2016-03-17 07:28
can I config C or C++ file extension name ?

**Comment by oulrich1** [comment] 2016-04-04 21:31
This problem was mentioned [here](https://github.com/atom/atom/issues/4156). 

One of the workarounds mentioned that I am using is from [here](https://github.com/atom/flight-manual.atom.io/blob/6e8baeecaf939426e66ee960c168cf27117215ef/book/02-using-atom/sections/06-customizing.asc#customizing-language-recognition). At the very bottom: "Customizing Language Recognition"

The workaround is to correctly update your config.cson under Atom > Config with:
`"*":
  core:
    customFileTypes:
      "source.cpp": [
        "h"
      ]
`

**Comment by thomasjo** [comment] 2016-04-05 05:44
Duplicate of #89. Can also be resolved using the `customFileTypes` feature, as described by @oulrich1

**Closed by thomasjo** 2016-04-05 05:44 UTC
