### ISSUE TITLE
"TODO" is not Colour Highlighted Anymore

### ISSUE THREAD

**Issue by JasonBaby87** [atom/language-c#298] opened 2018-10-24 03:11 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I just opened Atom today, and "TODO" is no longer highlighted like yesterday was.

### Steps to Reproduce

1. Open Atom
2. Open a .cpp file
3. Type "// TODO" without quotes

**Expected behavior:** "TODO" is highlighted from the rest of the comments

**Actual behavior:** "TODO" looks the same as the rest of the comments

**Reproduces how often:** 100%

### Versions

Atom    : 1.32.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0
python 2.7.15
git 2.15.0.windows.1
visual studio

OS: Windows 10 Home

### Additional Information

None.

**Comment by Ben3eeE** [comment] 2018-10-24 16:46
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-todo/issues/82. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-10-24 16:46 UTC
Labels: duplicate
