### ISSUE TITLE
The snippets are annoying me a lot

### ISSUE THREAD

**Issue by WillerZ** [atom/language-c#184] opened 2016-12-05 08:31 UTC
I fervently wish for a way to turn off the snippets for `once `, `cerr`, `cout`, `cin`, `enum`, `func`, `map`, `str` and `vector`. I have basically never wanted to write what they expand to and I often find them expanding as I write normal code and I press enter when they happen to appear on the end of a line. The expansion of `once` is the most frequently annoying; when I write:
```
#pragma once
```
changing that into:
```
#pragma #ifndef ${1:SYMBOL}
#define $1

${2}

#endif /* end of include guard: $1 */
```
is not at all helpful.

As I understand it at the moment there is no way to turn these off just for me. Is it possible to implement that? If not, is it possible to move the snippets into a separate package to layer on top of this so I can just uninstall them?

**Comment by Ben3eeE** [comment] 2016-12-05 09:17
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/snippets/issues/55. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

----

To answer your question. You can disable all snippets by disabling the snippets package. You could also change what they expand to so it is something you want to write.

**Closed by Ben3eeE** 2016-12-05 09:17 UTC
